name: Linux

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Tests
        run: |
          xmake -a
          xmake r flag -xy
          xmake r unitest -a -co_sched_num=4
          xmake f -m debug
          xmake -a