name: Windows

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Tests
        run: |
          xmake f -a ${{ matrix.arch }}
          xmake -a
          xmake r flag -xy
          xmake r unitest -a -noco
          xmake f -m debug -a ${{ matrix.arch }}
          xmake -a