name: Windows

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: xmake build & run unitest
        run: |
          xmake --confirm=n
          xmake r unitest -a